---
swagger: 2.0
info:
  title: obido-resize-image-prod
paths:
  /:
    get:
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:REGION:lambda:path/2015-03-31/functions/arn:aws:lambda:REGION:ACCOUNT_ID:function:${stageVariables.LambdaFunctionName}/invocations
        type: AWS_PROXY
        httpMethod: post
